"""Rule-based theme baseline (optional fallback when Groq is unavailable)."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any

from src.analysis.pipeline import stage_d_segments
from src.analysis.sampler import stratified_sample
from src.analysis.tags import is_discovery_candidate
from src.analysis.validators import validate_themes, validate_unmet_needs
from src.config import ANALYSIS_SAMPLE_CAP, PROCESSED_DIR
from src.ingestion.schema import NormalizedReview

THEME_RULES: list[dict[str, Any]] = [
    {
        "theme_id": "t1",
        "label": "Shuffle plays the same songs repeatedly",
        "pattern": re.compile(
            r"same (?:song|songs|few|20|50)|over and over|predict the next|"
            r"shuffle.{0,40}(?:garbage|joke|stuck|repeat)|replays? the same",
            re.I,
        ),
        "description": (
            "Users report shuffle and liked-song playback cycling through a small subset "
            "instead of their full library, reducing perceived discovery value."
        ),
    },
    {
        "theme_id": "t2",
        "label": "Unwanted recommendations injected into playlists",
        "pattern": re.compile(
            r"recommend|smart shuffle|random song|songs not on|inject|"
            r"not related to|stop (?:making|recommending)",
            re.I,
        ),
        "description": (
            "Listeners want control over what plays from their playlists; forced "
            "recommendations and smart shuffle break trust in curation."
        ),
    },
    {
        "theme_id": "t3",
        "label": "Home feed and discovery surfaces show non-music content",
        "pattern": re.compile(
            r"home page|audiobook|podcast|not recommending music|not one song|"
            r"discover weekly|release radar|for you",
            re.I,
        ),
        "description": (
            "Discovery surfaces prioritize podcasts, audiobooks, or stale picks instead "
            "of surfacing new music aligned with listening history."
        ),
    },
    {
        "theme_id": "t4",
        "label": "Algorithm misses taste or genre context",
        "pattern": re.compile(
            r"algorithm|wrong recommendation|spoils the vibe|cover song|"
            r"not new|feeds the same|dogshit songs|awful recommendation",
            re.I,
        ),
        "description": (
            "Recommendation quality feels misaligned with mood, genre, or freshness "
            "expectations — including repetitive or irrelevant suggestions."
        ),
    },
    {
        "theme_id": "t5",
        "label": "Free-tier limits block on-demand listening",
        "pattern": re.compile(
            r"can't (?:choose|pick|select)|premium feature|forced to shuffle|"
            r"6 skips|can't play|paywall",
            re.I,
        ),
        "description": (
            "Free users cannot reliably pick songs or control playback order, which "
            "directly limits intentional discovery and playlist listening."
        ),
    },
]

UNMET_PATTERN = re.compile(
    r"i wish|i want|why can't|why cant|bring back|please add|stop recommending|"
    r"let us|give us|option to",
    re.I,
)


def _best_quote(review: NormalizedReview, max_len: int = 180) -> str:
    body = review.body.strip()
    if len(body) <= max_len:
        return body
    trimmed = body[:max_len]
    if " " in trimmed:
        return trimmed.rsplit(" ", 1)[0]
    return trimmed


def _match_reviews(reviews: list[NormalizedReview], pattern: re.Pattern[str], limit: int = 40) -> list[NormalizedReview]:
    matched: list[NormalizedReview] = []
    for review in reviews:
        if pattern.search(review.body):
            matched.append(review)
    matched.sort(key=lambda r: (r.rating, -len(r.body)))
    return matched[:limit]


def _build_summary(label: str, description: str, count: int) -> str:
    return (
        f"{label} appears across {count} sampled reviews in this baseline run. "
        f"{description} "
        "This summary was generated by keyword clustering (no LLM) because Groq daily "
        "token quota was unavailable; re-run `python -m src.analysis.run` after quota reset "
        "for LLM-refined themes and quotes."
    )


def run_rule_baseline(
    reviews: list[NormalizedReview],
    seed: int = 42,
    sample_cap: int | None = None,
) -> dict[str, Any]:
    cap = sample_cap or min(ANALYSIS_SAMPLE_CAP, 450)
    sample_result = stratified_sample(reviews, total_cap=cap, seed=seed)
    sample = sample_result.reviews
    discovery = [r for r in sample if is_discovery_candidate(r.body)]
    pool = discovery if len(discovery) >= 30 else sample
    corpus = {r.review_id: r for r in sample}

    themes: list[dict] = []
    used_ids: set[str] = set()

    for rule in THEME_RULES:
        matched = _match_reviews(pool, rule["pattern"])
        matched = [r for r in matched if r.review_id not in used_ids]
        if not matched:
            continue
        rids = [r.review_id for r in matched[:25]]
        used_ids.update(rids)
        quote_reviews = matched[:3]
        themes.append(
            {
                "theme_id": rule["theme_id"],
                "label": rule["label"],
                "description": rule["description"],
                "supporting_review_ids": rids,
                "summary": _build_summary(rule["label"], rule["description"], len(matched)),
                "quotes": [
                    {"review_id": r.review_id, "text": _best_quote(r)} for r in quote_reviews
                ],
                "word_count": 0,
            }
        )
        themes[-1]["word_count"] = len(themes[-1]["summary"].split())
        if len(themes) >= 5:
            break

    unmet_rows: list[dict] = []
    for review in pool:
        if UNMET_PATTERN.search(review.body):
            unmet_rows.append(review)
    unmet_rows.sort(key=lambda r: r.rating)
    unmet_needs: list[dict] = []
    for rank, review in enumerate(unmet_rows[:5], start=1):
        stmt = _best_quote(review, max_len=120)
        unmet_needs.append(
            {
                "rank": rank,
                "statement": stmt,
                "supporting_review_ids": [review.review_id],
            }
        )

    segments = stage_d_segments(sample)
    theme_validation = validate_themes(themes, corpus)
    unmet_validation = validate_unmet_needs(unmet_needs, corpus)

    run_metadata = {
        "run_id": datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ"),
        "prompt_version": "rule_baseline_v1",
        "model_id": "rule-based-keyword-cluster",
        "seed": seed,
        "sample_size": len(sample),
        "unmet_subset_size": len(unmet_rows),
        "groq_call_count": 0,
        "estimated_tokens": 0,
        "cell_counts": sample_result.cell_counts,
        "theme_validation_ok": theme_validation.ok,
        "theme_validation_errors": theme_validation.errors,
        "unmet_validation_ok": unmet_validation.ok,
        "unmet_validation_errors": unmet_validation.errors,
    }

    return {
        "themes": themes,
        "unmet_needs": unmet_needs,
        "segments": segments,
        "run_metadata": run_metadata,
    }
